name: CD-WordGen-Agent
on:
  push:
    branches: [main]
    paths: ['apps/wordgen-agent/**']
jobs:
  deploy-agent:
    runs-on: [self-hosted, windows, win-word]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python deps
        shell: pwsh
        run: |
          py -3.11 -m pip install -r apps/wordgen-agent/requirements.txt
      - name: Restart service
        shell: pwsh
        run: |
          nssm stop WordGenAgent 2>$null
          nssm install WordGenAgent "C:\Python311\python.exe" "C:\actions\_work\rfp-proposal-platform\rfp-proposal-platform\apps\wordgen-agent\service.py"
          nssm set WordGenAgent AppDirectory "C:\actions\_work\rfp-proposal-platform\rfp-proposal-platform\apps\wordgen-agent"
          nssm set WordGenAgent Start SERVICE_AUTO_START
          nssm start WordGenAgent
