name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [apps/api, apps/workers/ocr]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd ${{ matrix.dir }}
          pip install -r requirements.txt
      - name: Lint placeholder
        run: echo "lint ok"
  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
